### ISSUE TITLE
Add Option to Break Harvest Block

### ISSUE THREAD

**Issue by Radiant-Xyz** [aratakileo/quick-harvest-plugin#1]
Hi there! I hope it's fine to request a feature here.

I would like to have an option to have the plugin break the harvest block and drop the items to the ground in order to collect them instead of putting them straight into the inventory. It is very convenient the way the plugin works right now but it is feeling far less rewarding.

I don't think this option would defeat the purpose of the plugin since automatic replanting itself and being able to hold down right click is still a breeze for harvesting large fields. It should probably not be the default configuration though as most people probably like the current behavior best.

**Comment by aratakileo** [comment]
Hi there! I think I can fulfill your request 👌

**Comment by Radiant-Xyz** [comment]
Thank you so much for adding the option I've requested! Also it's amazing how quickly you acted on it. Thank you.

I've had a chance to test it out and I think it adds exactly what I've been missing in the original implementation. I have a few other suggestions to further improve upon it though. I hope it's fine to add my thoughts here:

### Add Block Breaking Effect
I think it needs a bit more work to appear just like vanilla's block breaking. Firstly the particle animation is missing entirely and secondly the configured sound from the configuration still plays. Instead the block's breaking sound should play.

In order to help a bit with this change and not just ask I've researched a bit and I think this fuction adds at least the particles, maybe even the correct sound.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#playEffect(org.bukkit.Location,org.bukkit.Effect,T)
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html#STEP_SOUND

The block's Material can be accessed by calling getType on the Block and the Effect should probably be STEP_SOUND judging by the Enum's descriptions. The effect should be called on the world to make it visible to all players. This would override the custom sound which then probably only applies to dispensers. But since this might have the potential to cause some lag it would be best to make it configurable. Maybe by default the effect should be played only for the player themselves and optionally it's called on the world?

These are just some thoughts and possible implementation ideas. I've never written a server plugin before but seeing your commits helped me understand it all a bit better. I hope this is a help. Thank you again for your work!
